project:
  type: book
  output-dir: docs

book:
  title: "RS MINERVE Manuals"
  author: "Bastien ROQUIER, Javier FLUIXA SANMARTIN, Tristan BRAUCHLI, Theo BARACCHINI, Javier GARCIA HERNANDEZ, Alain FOEHN, Javier PAREDES ARQUIOLA, Giovanni DE CESARE"
  cover-image: figures/fig-cover_image.png
  site-url: https://crealp.github.io/rsminerve-releases/
  date: "05.02.2022"
  chapters:
    - index.qmd
    - part: user_manual.qmd
      chapters:
      - user_rainfall_runoff_modelling.qmd
      - user_hydraulic_infrastructures.qmd
      - user_database.qmd
      - user_gis.qmd
      - user_hydro_hydrau_simulation.qmd
      - user_expert_module.qmd
      - user_plugins.qmd      
    - part: tech_manual.qmd
      chapters:
      - tech_hydrological_models.qmd
      - tech_performance_indicators.qmd
      - tech_calibration_algorithms.qmd
      - tech_stochastic_equations.qmd
      - tech_scripts.qmd
      - tech_file_formats.qmd
      - tech_database_formats.qmd
      - tech_gis_formats.qmd 
    - part: examples.qmd
      chapters:
      - examples_ex1.qmd
      - examples_ex2.qmd
      - examples_ex3.qmd
      - examples_ex4.qmd
    - acknowledgments.qmd
  appendices:
      - appendix_list_param_ic.qmd
      - appendix_list_notifications.qmd

bibliography: references.bib

number-sections: true

title-block-banner: true

tbl-cap-location: top

link-citations: true

number-depth: 2

toc-depth: 4

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
editor: CREALP
