# List of notifications from pre-simulation and post-simulation reports {#sec-appendix_list_notifications}

The list of notifications (notes, warnings and fatal) of the pre- and
post-simulation reports is presented hereafter.

## Isolated objects

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------------+-------------------------+
| **Warning**  | If an object is isolated and is not       | **The object 'Object    |
|              | taken into account for calculation.       | 1' has no links and is  |
|              |                                           | isolated.**             |
+--------------+-------------------------------------------+-------------------------+

## Hydrology

### Virtual Station 

<span style="color:blue">Pre-Simulation Report</span>

+-------------+-------------------------------------+--------------------------+
| **Fatal**   | If a Virtual Station exists and is  | **Missing database to    |
|             | not isolated, but no database is    | get station data.**      |
|             | connected to the model.             |                          |
+-------------+-------------------------------------+--------------------------+
| **Fatal**   | If this object exists and a         | **No dataset is selected |
|             | database is connected to the        | for station 'Station     |
|             | hydrological model, but any dataset | 1' (X m, Y m, Z          |
|             | is selected for meteorological data | masl).**                 |
|             | utilisation.                        |                          |
+-------------+-------------------------------------+--------------------------+
| **Fatal**   | If this object exists and a         | **No datagroup is        |
|             | database is connected to the        | selected for station     |
|             | hydrological model, but no          | 'Station 1' (X m, Y m,   |
|             | datagroup is selected in the Data   | Z masl).**               |
|             | source.                             |                          |
+-------------+-------------------------------------+--------------------------+
| **Fatal**   | If this object exists and a         | **No precipitation       |
|             | database is connected to the        | values for station       |
|             | hydrological model, but a           | 'Station 1' (X m, Y m,   |
|             | precipitation input is not          | Z masl).**               |
|             | available in the database.          |                          |
+-------------+-------------------------------------+--------------------------+
| **Warning** | If this object exists and a         | **No temperature/ETP     |
|             | database is connected to the        | values for station       |
|             | hydrological model, but a           | 'Station 1' (X m, Y m,   |
|             | temperature / ETP input is not      | Z masl). A null series   |
|             | available.                          | will be considered.**    |
+-------------+-------------------------------------+--------------------------+

<span style="color:red">Post-Simulation Report</span>

+--------------+-----------------------------------------+--------------------------+
| **Warning**  | If this object does not find data       | **No precipitation found |
|              | for Precipitation, Temperature or       | 1within search radius of |
|              | ETP in any station of the database      |  virtual station         |
|              | within in the radius of search,         | 'Station 1'. Radius      |
|              | search radius is extended until         | extended to satisfy No.  |
|              | finding one.                            | min of stations.**       |
+--------------+-----------------------------------------+--------------------------+

\ 

### Snow-SD model description

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------+--------------------------+
| **Fatal**    | If this object exists and is        | **The object 'Snow-SD    |
|              | connected to other objects, but not | 1' has no Precipitation  |
|              | all Snow-SD model inputs are        | 'i' / Temperature        |
|              | available.                          | 'T' as input.**          |
+--------------+-------------------------------------+--------------------------+

\ 

### Runoff (SWMM) model description

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------+--------------------------+
| **Fatal**    | If the object exists and is not     | **The object 'SWMM 1'    |
|              | isolated, but has no intensity as   | has no Precipitation     |
|              | input.                              | 'i' as input.**          |
+--------------+-------------------------------------+--------------------------+

\ 

### GSM model description

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------+--------------------------+
| **Fatal**    | If this object exists and is not    | **The object 'GSM 1'     |
|              | isolated, but not all GSM model     | has no Precipitation     |
|              | inputs are available.               | 'P' / Temperature        |
|              |                                     | 'T' as input.**          |
+--------------+-------------------------------------+--------------------------+

\ 

### SOCONT model description

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------+--------------------------+
| **Fatal**    | If this object exists and is not    | **The object 'SOCONT     |
|              | isolated, but not all SOCONT model  | 1' has no Precipitation  |
|              | inputs are available.               | 'P' / Temperature        |
|              |                                     | 'T'/ETP 'ETP' as         |
|              |                                     | input.**                 |
+--------------+-------------------------------------+--------------------------+

\ 

### HBV model description

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------+--------------------------+
| **Fatal**    | If this object exists and is not    | **The object 'HBV 1'     |
|              | isolated, but not all HBV model     | has no Precipitation     |
|              | inputs are available.               | 'P'/Temperature          |
|              |                                     | 'T'/ETP 'ETP' as         |
|              |                                     | input.**                 |
+--------------+-------------------------------------+--------------------------+

\ 

### GR4J model description

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------+--------------------------+
|  **Fatal**   | If this object exists and is not    | **The object 'GR4J'      |
|              | isolated, but not all HBV model     | has no Precipitation     |
|              | inputs are available.               | 'P'/ETP 'ETP' as         |
|              |                                     | input.**                 |
+--------------+-------------------------------------+--------------------------+

\ 

### SAC model description

<span style="color:blue">Pre-simulation report</span>

+--------------+-------------------------------------+--------------------------+
| **Fatal**    | If this object exists and is not    | **The object 'SAC' has   |
|              | isolated, but not all SAC model     | no Precipitation         |
|              | inputs are available.               | 'P'/ETP 'ETP' as         |
|              |                                     | input.**                 |
+--------------+-------------------------------------+--------------------------+

## Rivers

### Channel routing description

No fatal, warnings or notes messages for this object.

## Standard objects

### Junction

No fatal, warnings or notes messages for this object.

### Time Series

<span style="color:blue">Pre-simulation report</span>

+--------------+--------------------------------------+--------------------------+
| **Fatal**    | If this object if used and is not    | **Times Series 'Time     |
|              | isolated, but the H-Q paired data is | series 1'is missing      |
|              | not provided.                        | paired data values.**    |
+--------------+--------------------------------------+--------------------------+

\ 

### Source

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Warning**  | If a source object exists and no      | **Missing database to    |
|              | database is connected to the model.   | get source data.**       |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If no group is selected in the Data   | **Missing database       |
|              |  source for sources.                  | group to source          |
|              |                                       | data.**                  |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If this object is used and is not     | **No station or sensor   |
|              | isolated, but the source has no a     | for source 'Source       |
|              | station from database to provide data | 1'.**                    |
|              | series.                               |                          |
+--------------+---------------------------------------+--------------------------+

### Comparator

No fatal errors, warnings or note messages for this object

### Sub-model

No fatal errors, warnings or note messages for this object

### Group Interface

No fatal errors, warnings or note messages for this object

## Structures objects

### Reservoir

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Fatal**    | If this object is used and is not     | **Reservoir 'Reservoir   |
|              | isolated, but the H-V paired data     | 1' is missing H-V        |
|              | is not provided.                      | paired data.**           |
+--------------+---------------------------------------+--------------------------+
| **Fatal**    | If this object is used and is not     | **The object 'Reservoir  |
|              | isolated, but does not have an        | 1' has no Flow 'Qe'      |
|              | inflow.                               | as input.**              |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If the initial level of the           | **Hini of reservoir      |
|              | reservoir is out of the range         | 'Reservoir 1'is out of   |
|              | proposed in the H-V paired data.      | range.**                 |
|              | The simulation is achieved,           |                          |
|              | assuming the level equals to the      |                          |
|              | maximum level of the reservoir.       |                          |
+--------------+---------------------------------------+--------------------------+
| **Note**     | If a Reservoir object exists but no   | **Missing database to    |
|              | database is connected to the model.   | get initial height of    |
|              |                                       | reservoirs.**            |
+--------------+---------------------------------------+--------------------------+
| **Note**     | If no group is selected in the Data   | **Missing database group |
|              | source for reservoirs.                | to get HPP data.**       |
+--------------+---------------------------------------+--------------------------+
| **Note**     | If the reservoir uses the initial     | **Hini of reservoir      |
|              | condition proposed by the user (and   | 'Reservoir 1'used as     |
|              | not data from database as initial     | initial height.**        |
|              | condition).                           |                          |
+--------------+---------------------------------------+--------------------------+
| **Note**     | If the reservoir uses the initial     | **Initial height of      |
|              | condition from the database.          | reservoir 'Reservoir     |
|              |                                       | 1' taken from            |
|              |                                       | database.**              |
+--------------+---------------------------------------+--------------------------+

<span style="color:red">Post-Simulation Report</span>

+--------------+---------------------------------------+--------------------------+
| **Warning**  | If the volume becomes negative in a   | **Volume of reservoir    |
|              | moment of the simulation.             |'Reservoir 1' contains    |
|              | Nevertheless, the simulation is       |negative values.**        |
|              | computed (with a correct volume       |                          |
|              | variation, V; keeping the reservoir   |                          |
|              | level, H, in zero for negative        |                          |
|              | volumes).                             |                          |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If the volume exceeds the maximum     | **Volume of reservoir    |
|              | volume proposed in the relation       | 'Reservoir 1' exceeds    |
|              | H-V. Nevertheless, the simulation     | its capacity.**          |
|              | is computed (with a correct volume    |                          |
|              | variation, V, keeping the reservoir   |                          |
|              | level, H, to maximum value of         |                          |
|              | paired data H-V when volume exceeds   |                          |
|              | the maximum volume).                  |                          |
+--------------+---------------------------------------+--------------------------+

\ 

### HQ

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Fatal**    | If this object is used and is not     | **HQ 'HQ 1'is missing    |
|              | isolated, but the H-Q paired data is  | H-Q paired data.**       |
|              | not provided.                         |                          |
+--------------+---------------------------------------+--------------------------+

<span style="color:red">Post-Simulation Report</span>

+--------------+---------------------------------------+--------------------------+
| **Warning**  | The computed simulation runs even     | **The maximum level of   |
|              | if the level is equal or over the     | HQ 'HQ 1' has been       |
|              | maximum level proposed in the         | attained or exceeded.**  |
|              | relation H-Q. In that case, the       |                          |
|              | outflow is kept as the maximum        |                          |
|              | discharge existing in the relation    |                          |
|              | H-Q.                                  |                          |
+--------------+---------------------------------------+--------------------------+

\ 

### Turbine

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Fatal**    | If this object is used and is not     |**The object 'Turbine     |
|              | isolated, but do not receive the      | 1' has no Flow           |
|              | Q~wanted~ data as input.              | 'Qwanted' as input.**    |
+--------------+---------------------------------------+--------------------------+

\ 

### TurbineDB

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Warning**  | If a TurbineDB object exists and no   | **Missing                |
|              | database is connected to the model.   | database to              |
|              |                                       | get TurbineDB            |
|              |                                       | data.**                  |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If this object if used and is not     | **Missing database       |
|              | isolated, but no group is selected    | group to get TurbineDB   |
|              | in the Data source for TurbineDB.     | data.**                  |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If this object if used and is not     | **No station             |
|              | isolated, but the TurbineDB has not   | or sensor for            |
|              | a station from database to provide    | TurbineDB                |
|              | data series.                          | 'TurbineDB               |
|              |                                       | 1'.**                    |
+--------------+---------------------------------------+--------------------------+

\ 

### Hydropower

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Fatal**    | If this object if used and is not     | **Hydropower             |
|              | isolated, but the Q-η paired data     | 'Hydropower              |
|              | is not provided.                      | 1'is missing             |
|              |                                       | paired data              |
|              |                                       | values.**                |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If a source object exists and no      | **Missing database to    |
|              | database is connected to the model.   | get Hydropower data.     |
|              |                                       | Default Price value(s)   |
|              |                                       | will be used.**          |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If no group is selected in the Data   | **Missing database       |
|              | source for sources.                   | group to get             |
|              |                                       | Hydropower data.         |
|              |                                       | Default Price value(s)   |
|              |                                       | will be used.**          |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If this object is used and is not     | **No station or sensor   |
|              | isolated, but the consumer has not    | for Hydropower           |
|              | a station from database to provide    | 'Hydropower 1'.          |
|              | data series.                          | Price defined from       |
|              |                                       | Default Price.**         |
+--------------+---------------------------------------+--------------------------+

\ 

### Diversion

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Fatal**    | If this object if used and is not     | **Diversion 'Diversion   |
|              | isolated, but the Q~Up~-Q~Diverted~   | 1'is missing             |
|              | paired data is not provided.          | QUp-QDiverted paired     |
|              |                                       | data.**                  |
+--------------+---------------------------------------+--------------------------+

\ 

### Consumer

<span style="color:blue">Pre-simulation report</span>

+--------------+---------------------------------------+--------------------------+
| **Warning**  | If a source object exists and no      | **Missing database to    |
|              | database is connected to the model.   | get Consumer data.       |
|              |                                       | Default QDemand values   |
|              |                                       | will be used.**          |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If no group is selected in the Data   | **Missing database       |
|              | source for sources.                   | group to consumer        |
|              |                                       | data. Default QDemand    |
|              |                                       | values will be used.**   |
+--------------+---------------------------------------+--------------------------+
| **Warning**  | If this object is used and is not     | **No station or sensor   |
|              | isolated, but the consumer has not a  | for Consumer             |
|              | station from database to provide data | 'Consumer 1'.            |
|              | series.                               | Consumption defined      |
|              |                                       | from Default             |
|              |                                       | QDemand.**               |
+--------------+---------------------------------------+--------------------------+

## Planner object

### Planner

<span style="color:blue">Pre-simulation report</span>

+----------+-----------------------+-----------------------------+
| **Fatal  | A rule in required.   | **The planner 'Planner      |
|  Error** |                       | 1' has no rules defined.**  |
+----------+-----------------------+-----------------------------+

\ 

### Rules

<span style="color:blue">Pre-simulation report</span>

+----------+--------------------------+--------------------------+
| **Fatal  | A condition is required. | **The rule 'Rule 1' in   |
|  Error** |                          | planer 'Planner 1' has   |
|          |                          | no condition defined.**  |
+----------+--------------------------+--------------------------+

\ 

### Conditions

<span style="color:blue">Pre-simulation report</span>

+----------+--------------------------+--------------------------+
| **Fatal  | An input is required.    | **The condition          |
|  Error** |                          | 'Condition 1' in 'Rule   |
|          |                          | 1' of ' Planner 10 has   |
|          |                          | no input defined.**      |
+----------+--------------------------+--------------------------+
| **Fatal  | An object is required.   | **The condition          |
|  Error** |                          | 'Condition 1' in 'Rule   |
|          |                          | 1' of ' Planner 10 has   |
|          |                          | no object defined.**     |
+----------+--------------------------+--------------------------+
| **Fatal  | A result is required.    | **The condition          |
|  Error** |                          | 'Condition 1' in 'Rule   |
|          |                          | 1' of ' Planner 10 has   |
|          |                          | no result defined.**     |
+----------+--------------------------+--------------------------+
