# Appendix: List of parameters and initial conditions   {#sec-appendix_list_param_ic}

The list of parameters and initials conditions of the different
objets in RS MINERVE is presented hereafter.

## Hydrology models

+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Name                 | Units   | Description                                                                              | Regular Range    |
+======================+=========+==========================================================================================+==================+
| X, Y, Z              | \-      | Coordinates of the virtual station                                                       | \-               |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Search Radius        | m       | Search radius of the virtual stations                                                    | \>0              |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| No. min. of stations | \-      | Minimal number of stations used for interpolation (higher priority than "Search Radius") | $\geq$ 1         |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Gradient P           | 1/m     | Precipitation gradient                                                                   | \-[^app_param_1] |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Gradient T           | °C/m    | Temperature gradient                                                                     | -0.007 to -0.004 |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Gradient ETP         | 1/m     | Evapotranspiration gradient                                                              | \-[^app_param_1] |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Coeff P              | \-      | Multiplying correction coefficient                                                       | 0.5 to 2         |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Coeff T              | °C      | Adding correction coefficient                                                            | -2 to 2          |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+
| Coeff ETP            | \-      | Multiplying correction coefficient                                                       | 0.5 to 2         |
+----------------------+---------+------------------------------------------------------------------------------------------+------------------+

: List of parameters for the **virtual station** {#tbl-app_param_virtual_station}

[^app_param_1]: The precipitation and potential evapotranspiration gradients 
are function of the local conditions. Their regular ranges have to be estimated 
for each studied case.

\ 

+------------+-----------+-------------------------------------------------------+-------------------+
| Name       | Units     | Decription                                            | Regular range     |
+============+===========+=======================================================+===================+
| S          | mm/°C/d   | Reference degree-day snowmelt coefficient             | 0.5 to 20         |
+------------+-----------+-------------------------------------------------------+-------------------+
| SInt       | mm/°C/d   | Degree-day snowmelt interval                          | 0 to 4            |
+------------+-----------+-------------------------------------------------------+-------------------+
| SMin       | mm/°C/d   | Minimal degree-day snowmelt coefficient               | $\geq$ 0          |
+------------+-----------+-------------------------------------------------------+-------------------+
| SPh        | d         | Phase shift of the sinusoidal function                | 1 to 365          |
+------------+-----------+-------------------------------------------------------+-------------------+
| ThetaCri   | \-        | Critical relative water content of the snow pack      | 0.1               |
+------------+-----------+-------------------------------------------------------+-------------------+
| bp         | d/mm      | Melt coefficient due to liquid precipitation          | 0.0125            |
+------------+-----------+-------------------------------------------------------+-------------------+
| Tcp1       | °C        | Minimum critical temperature for liquid precipitation | 0                 |
+------------+-----------+-------------------------------------------------------+-------------------+
| Tcp2       | °C        | Maximum critical temperature for solid precipitation  | 4                 |
+------------+-----------+-------------------------------------------------------+-------------------+
| Tcf        | °C        | Critical snowmelt temperature                         | 0                 |
+------------+-----------+-------------------------------------------------------+-------------------+
| CFR        | \-        | Refreezing coefficient                                | 0 to 1            |
+------------+-----------+-------------------------------------------------------+-------------------+
| *SWEIni*   | m         | Initial snow water equivalent height                  | \-                |
+------------+-----------+-------------------------------------------------------+-------------------+
| *ThetaIni* | \-        | Initial relative water content in the snow pack       | \-                |
+------------+-----------+-------------------------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **Snow-SD model** {#tbl-app_param_model_snow}

\ 

+----------+-----------+-----------------------------------------------+-------------------+
| Name     | Units     | Description                                   | Regular Range     |
+==========+===========+===============================================+===================+
| A        | m^2^      | Surface of runoff                             | \>0               |
+----------+-----------+-----------------------------------------------+-------------------+
| L        | m         | Length of the plane                           | \>0               |
+----------+-----------+-----------------------------------------------+-------------------+
| J0       | \-        | Runoff slope                                  | \>0               |
+----------+-----------+-----------------------------------------------+-------------------+
| K        | m^1/3^/s  | Strickler coefficient                         | 0.1 to 90         |
+----------+-----------+-----------------------------------------------+-------------------+
| *HIni*   | m         | Initial water level downstream of the surface | \-                |
+----------+-----------+-----------------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **SWMM model** {#tbl-app_param_model_swmm}

\ 

+---------------+-----------+-------------------------------------------------------+-------------------+
| Name          | Units     | Description                                           | Regular Range     |
+===============+===========+=======================================================+===================+
| A             | m^2^      | Surface of infiltration                               | \>0               |
+---------------+-----------+-------------------------------------------------------+-------------------+
| S             | mm/°C/d   | Reference degree-day snowmelt coefficient             | 0.5 to 20         |
+---------------+-----------+-------------------------------------------------------+-------------------+
| SInt          | mm/°C/d   | Degree-day snowmelt interval                          | 0 to 4            |
+---------------+-----------+-------------------------------------------------------+-------------------+
| SMin          | mm/°C/d   | Minimal degree-day snowmelt coefficient               | $\geq$ 0          |
+---------------+-----------+-------------------------------------------------------+-------------------+
| Sph           | d         | Phase shift of the sinusoidal function                | 1 to 365          |
+---------------+-----------+-------------------------------------------------------+-------------------+
| ThetaCri      | \-        | Critical relative water content of the snow pack      | 0.1               |
+---------------+-----------+-------------------------------------------------------+-------------------+
| bp            | d/mm      | Melt coefficient due to liquid precipitation          | 0.0125            |
+---------------+-----------+-------------------------------------------------------+-------------------+
| Tcp1          | °C        | Minimum critical temperature for liquid precipitation | 0                 |
+---------------+-----------+-------------------------------------------------------+-------------------+
| Tcp2          | °C        | Maximum critical temperature for solid precipitation  | 4                 |
+---------------+-----------+-------------------------------------------------------+-------------------+
| Tcf           | °C        | Critical snowmelt temperature                         | 0                 |
+---------------+-----------+-------------------------------------------------------+-------------------+
| G             | mm/°C/d   | Reference degree-day glacier melt coefficient         | 0.5 to 20         |
+---------------+-----------+-------------------------------------------------------+-------------------+
| GInt          | mm/°C/d   | Degree-day glacier melt interval                      | 0 to 4            |
+---------------+-----------+-------------------------------------------------------+-------------------+
| GMin          | mm/°C/d   | Minimal degree-day glacier melt coefficient           | $\geq$ 0          |
+---------------+-----------+-------------------------------------------------------+-------------------+
| Tcg           | °C        | Critical glacier melt temperature                     | 0                 |
+---------------+-----------+-------------------------------------------------------+-------------------+
| Kgl           | 1/d       | Release coefficient of glacier melt reservoir         | 0.1 to 5          |
+---------------+-----------+-------------------------------------------------------+-------------------+
| Ksn           | 1/d       | Release coefficient of snowmelt reservoir             | 0.1 to 5          |
+---------------+-----------+-------------------------------------------------------+-------------------+
| CFR           | \-        | Refreezing coefficient                                | 0 to 1            |
+---------------+-----------+-------------------------------------------------------+-------------------+
| *SWEIni*      | m         | Initial snow water equivalent height                  | \-                |
+---------------+-----------+-------------------------------------------------------+-------------------+
| *ThetaIni*    | \-        | Initial relative water content in the snow pack       | \-                |
+---------------+-----------+-------------------------------------------------------+-------------------+
| *QsnowIni*    | m^3^/s    | Initial outflow of linear snow reservoir              | \-                |
+---------------+-----------+-------------------------------------------------------+-------------------+
| *QglacierIni* | m^3^/s    | Initial outflow of linear glacier reservoir           | \-                |
+---------------+-----------+-------------------------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **GSM model** {#tbl-app_param_model_gsm}

\ 

+------------+-----------+-------------------------------------------------------+-------------------+
| Name       | Units     | Description                                           | Regular Range     |
+============+===========+=======================================================+===================+
| A          | m^2^      | Surface                                               | \>0               |
+------------+-----------+-------------------------------------------------------+-------------------+
| S          | mm/°C/d   | Reference degree-day snowmelt coefficient             | 0.5 to 20         |
+------------+-----------+-------------------------------------------------------+-------------------+
| SInt       | mm/°C/d   | Degree-day snowmelt interval                          | 0 to 4            |
+------------+-----------+-------------------------------------------------------+-------------------+
| SMin       | mm/°C/d   | Minimal degree-day snowmelt coefficient               | $\geq$ 0          |
+------------+-----------+-------------------------------------------------------+-------------------+
| SPh        | d         | Phase shift of the sinusoidal function                | 1 to 365          |
+------------+-----------+-------------------------------------------------------+-------------------+
| ThetaCri   | \-        | Critical relative water content of the snow pack      | 0.1               |
+------------+-----------+-------------------------------------------------------+-------------------+
| bp         | d/mm      | Melt coefficient due to liquid precipitation          | 0.0125            |
+------------+-----------+-------------------------------------------------------+-------------------+
| Tcp1       | °C        | Minimum critical temperature for liquid precipitation | 0                 |
+------------+-----------+-------------------------------------------------------+-------------------+
| Tcp2       | °C        | Maximum critical temperature for solid precipitation  | 4                 |
+------------+-----------+-------------------------------------------------------+-------------------+
| Tcf        | °C        | Critical snowmelt temperature                         | 0                 |
+------------+-----------+-------------------------------------------------------+-------------------+
| HGR3Max    | m         | Maximum height of infiltration reservoir              | 0 to 2            |
+------------+-----------+-------------------------------------------------------+-------------------+
| KGR3       | 1/s       | Release coefficient of infiltration reservoir         | 0.00025 to 0.1    |
+------------+-----------+-------------------------------------------------------+-------------------+
| L          | m         | Length of the plane                                   | \>0               |
+------------+-----------+-------------------------------------------------------+-------------------+
| J0         | \-        | Runoff slope                                          | \>0               |
+------------+-----------+-------------------------------------------------------+-------------------+
| Kr         | m^1/3^/s  | Strickler coefficient                                 | 0.1 to 90         |
+------------+-----------+-------------------------------------------------------+-------------------+
| CFR        | \-        | Refreezing coefficient                                | 0 to 1            |
+------------+-----------+-------------------------------------------------------+-------------------+
| *SWEIni*   | m         | Initial snow water equivalent height                  | \-                |
+------------+-----------+-------------------------------------------------------+-------------------+
| *HGR3Ini*  | m         | Initial level in infiltration reservoir               | \-                |
+------------+-----------+-------------------------------------------------------+-------------------+
| *HrIni*    | m         | Initial runoff water level downstream of the surface  | \-                |
+------------+-----------+-------------------------------------------------------+-------------------+
| *ThetaIni* | \-        | Initial relative water content in the snow pack       | \-                |
+------------+-----------+-------------------------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **SOCONT model** {#tbl-app_param_model_socont}

\ 

+----------+-----------+--------------------------------------------------+-------------------+
| Name     | Units     | Description                                      | Regular Range     |
+==========+===========+==================================================+===================+
| A        | m^2^      | Surface of the basin                             | \>0               |
+----------+-----------+--------------------------------------------------+-------------------+
| CFMax    | mm/°C/d   | Melting factor                                   | 0.5 to 20         |
+----------+-----------+--------------------------------------------------+-------------------+
| CFR      | \-        | Refreezing factor                                | 0.05              |
+----------+-----------+--------------------------------------------------+-------------------+
| CWH      | \-        | Critical relative water content of the snow pack | 0.1               |
+----------+-----------+--------------------------------------------------+-------------------+
| TT       | °C        | Threshold temperature of rain/snow               | 0 to 3            |
+----------+-----------+--------------------------------------------------+-------------------+
| TTInt    | °C        | Temperature interval for rain/snow mixing        | 0 to 3            |
+----------+-----------+--------------------------------------------------+-------------------+
| TTSM     | °C        | Threshold temperature for snow melt              | 0                 |
+----------+-----------+--------------------------------------------------+-------------------+
| Beta     | \-        | Model parameter (shape coefficient)              | 1 to 5            |
+----------+-----------+--------------------------------------------------+-------------------+
| FC       | m         | Maximum soil storage capacity                    | 0.050 to 0.65     |
+----------+-----------+--------------------------------------------------+-------------------+
| PWP      | \-        | Soil permanent wilting point threshold           | 0.030 to 1        |
+----------+-----------+--------------------------------------------------+-------------------+
| SUMax    | m         | Upper reservoir water level threshold            |  0 to 0.10        |
+----------+-----------+--------------------------------------------------+-------------------+
| Kr       | 1/d       | Near surface flow storage coefficient            | 0.05 to 0.5       |
+----------+-----------+--------------------------------------------------+-------------------+
| Ku       | 1/d       | Interflow storage coefficient                    | 0.01 to 0.4       |
+----------+-----------+--------------------------------------------------+-------------------+
| Kl       | 1/d       | Baseflow storage coefficient                     | 0 to 0.15         |
+----------+-----------+--------------------------------------------------+-------------------+
| Kperc    | 1/d       | Percolation storage coefficient                  | 0 to 0.8          |
+----------+-----------+--------------------------------------------------+-------------------+
| *SWEIni* | m         | Initial snow water equivalent height             | \-                |
+----------+-----------+--------------------------------------------------+-------------------+
| *WHIni*  | \-        | Initial relative water content in the snow pack  | \-                |
+----------+-----------+--------------------------------------------------+-------------------+
| *HumIni* | m         | Initial humidity                                 | \-                |
+----------+-----------+--------------------------------------------------+-------------------+
| *SUIni*  | m         | Initial upper reservoir water level              | \-                |
+----------+-----------+--------------------------------------------------+-------------------+
| *SLIni*  | m         | Initial lower reservoir water level              | \-                |
+----------+-----------+--------------------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **HBV model** {#tbl-app_param_model_hbv}

\ 

+----------+-----------+---------------------------------------------------+-------------------+
| Name     | Units     | Description                                       | Regular Range     |
+==========+===========+===================================================+===================+
| A        | m^2^      | Surface of the basin                              | \>0               |
+----------+-----------+---------------------------------------------------+-------------------+
| X1       | m         | Capacity of production store                      | 0.01 to 1.2       |
+----------+-----------+---------------------------------------------------+-------------------+
| X2       | m         | Water exchange coefficient                        | -0.005 to 0.003   |
+----------+-----------+---------------------------------------------------+-------------------+
| X3       | m         | Capacity of routing store                         | 0.01 to 0.5       |
+----------+-----------+---------------------------------------------------+-------------------+
| X4       | d         | UH time base                                      | -0.5 to 1         |
+----------+-----------+---------------------------------------------------+-------------------+
| *SIni*   | m         | Initial water content in the production reservoir | \-                |
+----------+-----------+---------------------------------------------------+-------------------+
| *RIni*   | m         | Initial water level in the routing reservoir      | \-                |
+----------+-----------+---------------------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **GR4J model** {#tbl-app_param_model_gr4j}

\ 

+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Name      | Units     | Description                                                                    | Regular Range     |
+===========+===========+================================================================================+===================+
| A         | m^2^      | Surface of the basin                                                           | \>0               |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Adimp     | \-        | Maximum fraction of an additional impervious area due to saturation            | 0 to 0.2          |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Pctim     | \-        | Permanent impervious area fraction                                             | 0 to 0.05         |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Riva      | \-        | Riparian vegetarian area fraction                                              | 0 to 0.2          |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| UztwMax   | m         | Upper Zone Tension Water capacity                                              | 0.01 to 0.15      |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| UzfwMax   | m         | Upper Zone Free Water capacity                                                 | 0.005 to 0.10     |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Uzk       | 1/d       | Interflow depletion rate from the Upper Zone Free Water storage                | 0.10 to 0.75      |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Zperc     | \-        | Ratio of maximum and minimum percolation rates                                 | 10 to 350         |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Rexp      | \-        | Shape parameter of the percolation curve                                       | 1 to 4            |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Pfree     | \-        | Percolation fraction that goes directly to the Lower Zone Free Water storages  | 0 to0.6           |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| LztwMax   | m         | The Lower Zone Tension Water capacity                                          | 0.05 to 0.40      |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| LzfpMax   | m         | The Lower Zone primary Free Water capacity                                     | 0.03 to 0.80      |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| LzfsMax   | m         | The Lower Zone supplementary Free Water capacity                               | 0.01 to 0.40      |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Rserv     | \-        | Fraction of Lower Zone Free Water not transferable to Lower Zone Tension Water | 0 to 1            |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Lzpk      | 1/d       | Depletion rate of the Lower Zone primary Free Water storage                    | 0.001 to 0.03     |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Lzsk      | 1/d       | Depletion rate of the Lower Zone supplemental Free Water storage               | 0.02 to 0.3       |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| Side      | \-        | Ratio of deep percolation from Lower Zone Free Water storages                  | 0 to 0.5          |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| *AdimIni* | m         | Initial Tension Water content of the Adimp area                                | \-                |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| *UztwIni* | m         | Initial Upper Zone Tension Water content                                       | \-                |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| *UzfwIni* | m         | Initial Upper Zone Free Water content                                          | \-                |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| *LztwIni* | m         | Initial Lower Zone Tension Water content                                       | \-                |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| *LzfpIni* | m         | Initial Lower Zone Free supplementary content                                  | \-                |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+
| *LzfsIni* | m         | Initial Lower Zone Free primary content                                        | \-                |
+-----------+-----------+--------------------------------------------------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **SAC-SMA model** {#tbl-app_param_model_sac_sma}

\ 

+----------+-----------+----------------------+-------------------+
| Name     | Units     | Description          | Regular Range     |
+==========+===========+======================+===================+
| A        | m^2^      | Surface of the basin | \>0               |
+----------+-----------+----------------------+-------------------+
| CN       | \-        | Curve Number         | 30 to 100         |
+----------+-----------+----------------------+-------------------+
| L        | m         | Width of the plane   | $\geq$ 0          |
+----------+-----------+----------------------+-------------------+
| J0       | \-        | Runoff slope         | \geq 0            |
+----------+-----------+----------------------+-------------------+
| *Ia*     | mm        | Initial abstraction  | 0 to 100000       |
+----------+-----------+----------------------+-------------------+
| TI       | s         | Lag time             | $\geq$ 0          |
+----------+-----------+----------------------+-------------------+

: List of parameters and *initial conditions* for the **SCS model** {#tbl-app_param_model_scs}

## River models

+----------+----------+----------------------------------------+-------------------+
| Name     | Units    | Description                            | Regular Range     |
+==========+==========+========================================+===================+
| L        | m        | Length                                 | \>0               |
+----------+----------+----------------------------------------+-------------------+
| B0       | m        | Width of the channel base              | \>0               |
+----------+----------+----------------------------------------+-------------------+
| m        | \-       | Side bank relation coefficient (1H/mV) | 0.1 to 1          |
+----------+----------+----------------------------------------+-------------------+
| J0       | \-       | Slope                                  | \>0               |
+----------+----------+----------------------------------------+-------------------+
| K        | m^1/3^/s | Strickler coefficient                  | 10 to 90          |
+----------+----------+----------------------------------------+-------------------+
| N        | \-       | Number of sections (not for Lag-Time)  | \>0               |
+----------+----------+----------------------------------------+-------------------+
| Lag      | min      | Lag time (only for Lag-Time)           | $\geq$ 0          |
+----------+----------+----------------------------------------+-------------------+
| *QIni*   | m^3^/s   | Initial discharge                      | \-                |
+----------+----------+----------------------------------------+-------------------+

: List of parameters and *initial conditions* for the **channel routing model** {#tbl-app_param_model_channel_routing}

## Standard models

+---------------+-------------------------------+----------------------+
| Name          | Units                         | Description          |
+===============+===============================+======================+
| Series        | s (depending on the series)   | Time - Value series  |
| (paired data) |                               |                      |
+---------------+-------------------------------+----------------------+

: **Time series** required data {#tbl-app_param_model_timeseries}

## Infrastructure objects

+---------------+--------------+--------------------------------+
| Name          | Units        | Description                    |
+===============+==============+================================+
| H-V           | masl - m^3^  | Level - Volume relation        |
| (paired data) |              |                                |
+---------------+--------------+--------------------------------+
| *Hini*        | masl         | Initial level in the reservoir |
+---------------+--------------+--------------------------------+

: **Reservoir** paired data and *initial condition* required {#tbl-app_param_model_reservoir}

\ 

+---------------+---------------+----------------------------+
| Name          | Units         | Description                |
+===============+===============+============================+
| H-Q           | masl - m^3^/s | Level - Discharge relation |
| (paired data) |               |                            |
+---------------+---------------+----------------------------+

: **HQ** paired data required {#tbl-app_param_model_hq}

\ 

+------------------+---------------+-------------------------------------------------------------------------------+
| Name             | Units         | Description                                                                   |
+==================+===============+===============================================================================+
| H-Q              | masl - m^3^/s | Level - Discharge relation                                                    |
| (paired data)    |               |                                                                               |
+------------------+---------------+-------------------------------------------------------------------------------+
| Hon              | masl          | Threshold in the level of the reservoir to start the turbine cycle            |
|                  |               | (turbine starts when the threshold is exceeded)                               |
+------------------+---------------+-------------------------------------------------------------------------------+
| Hoff             | masl          | Threshold in the level of the reservoir to stop the turbine cycle             |
|                  |               | (turbine stops when level go below the threshold)                             |
+------------------+---------------+-------------------------------------------------------------------------------+
| *IsOperatingIni* | 0/1           | First suggested value for the turbine cycle                                   |
|                  |               | (0 = not turbine; 1 = turbine). Only taken into account if *Hoff \> H \> Hon* |
+------------------+---------------+-------------------------------------------------------------------------------+

: **Time-Q** paired data, parameters and *initial condition* required {#tbl-app_param_model_turbine}

\ 

+---------------+-----------------+------------------------------------------------------------+
| Name          | Units           | Description                                                |
+===============+=================+============================================================+
| Q-\eta        | m\^ 3\^/s - \%  | Discharge-Performance relation                             |
| (paired data) |                 |                                                            |
+---------------+-----------------+------------------------------------------------------------+
| Zplant        | masl            | Hydropower plant altitude                                  |
+---------------+-----------------+------------------------------------------------------------+
| L             | m               | Length of the pipe                                         |
+---------------+-----------------+------------------------------------------------------------+
| D             | m               | Diameter of the pipe                                       |
+---------------+-----------------+------------------------------------------------------------+
| K             | m               | Roughness                                                  |
+---------------+-----------------+------------------------------------------------------------+
| \nu           | m^2^/s          | Kinematic viscosity                                        |
+---------------+-----------------+------------------------------------------------------------+
| Default Price | €/Kwh           | Default price, only used if no data exists in the database |
+---------------+-----------------+------------------------------------------------------------+

: **Hydropower** paired data and parameters required {#tbl-app_param_model_hydropower}

\ 

+----------------------+-----------------+----------------------------------------+
| Name                 | Units           | Description                            |
+======================+=================+========================================+
| Q~up~-Q~diverted~    | m^3^/s - m^3^/s | Upstream flow - Diverted flow relation |
| (paired data)        |                 |                                        |
+----------------------+-----------------+----------------------------------------+

: **Diversion** paired data required {#tbl-app_param_model_diversion}

\ 

+-----------------+-----------+-----------------------------------------------------------------------------+
| Name            | Units     | Description                                                                 |
+=================+===========+=============================================================================+
| LossRate        | \-        | Fraction of the *Q~supplied~* lost at the demand site                       |
+-----------------+-----------+-----------------------------------------------------------------------------+
| ConsumptionRate | \-        | Fraction of the *Q~delivered~* ultimately consumed                          |
+-----------------+-----------+-----------------------------------------------------------------------------+
| Default QDemand | m^3^/s    | Default demand of consummation, only used if no data exists in the database |
+-----------------+-----------+-----------------------------------------------------------------------------+

: **Consumer** parameters required {#tbl-app_param_model_consumer}

\ 

+-------------+-------------+-----------------------------+
| Name        | Units       | Description                 |
+=============+=============+=============================+
| Efficiency  | \-          | Efficiency of the structure |
+-------------+-------------+-----------------------------+

: **Structure efficiency** parameters required {#tbl-app_param_model_efficiency}
