<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.315">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>RS MINERVE Manuals - 10&nbsp; Calibration algorithms</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<link href="./tech_stochastic_equations.html" rel="next">
<link href="./tech_performance_indicators.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link id="quarto-text-highlighting-styles" href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Calibration algorithms</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span id="sec-tech_calibration_algorithms" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Calibration algorithms</span></span></h1>
                </div>
  </div>
    
  



  <div class="quarto-title-meta">

      
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">RS MINERVE Manuals</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./user_manual.html" class="sidebar-item-text sidebar-link">User Manual</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./user_rainfall_runoff_modelling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Rainfall-runoff modelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./user_hydraulic_infrastructures.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Hydraulic infrastructures modelling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./user_database.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Database</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./user_gis.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">GIS</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./user_hydro_hydrau_simulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hydrological-hydraulic simulation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./user_expert_module.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Expert module</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./user_plugins.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Plugins</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./tech_manual.html" class="sidebar-item-text sidebar-link">Technical Manual</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_hydrological_models.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Hydrological and hydraulics models description</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_performance_indicators.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Performance indicators</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_calibration_algorithms.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Calibration algorithms</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_stochastic_equations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Stochastic equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_scripts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Visual Basic Scripts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_file_formats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">File formats</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_database_formats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Database formats</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tech_gis_formats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">GIS formats</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="./examples.html" class="sidebar-item-text sidebar-link">Examples of application</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./examples_ex1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Example 1 – Simple basin with only runoff</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./examples_ex2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Example 2 – Combined full basin with meteorological stations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./examples_ex3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Example 3 – Equipped basin with a hydropower scheme</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./examples_ex4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Example 4 – Automatic calibration of a model</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowledgments.html" class="sidebar-item-text sidebar-link">Acknowledgments</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Appendices</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_list_param_ic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Appendix: List of parameters and initial conditions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_list_notifications.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">List of notifications from pre-simulation and post-simulation reports</span></a>
  </div>
</li>
    </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-tech_calibration_algorithms_intro" id="toc-sec-tech_calibration_algorithms_intro" class="nav-link active" data-scroll-target="#sec-tech_calibration_algorithms_intro"> <span class="header-section-number">10.1</span> Introduction to the calibration module</a></li>
  <li><a href="#sec-tech_calibration_algorithms_of" id="toc-sec-tech_calibration_algorithms_of" class="nav-link" data-scroll-target="#sec-tech_calibration_algorithms_of"> <span class="header-section-number">10.2</span> Objective function</a></li>
  <li><a href="#sec-tech_calibration_algorithms_sce_ua" id="toc-sec-tech_calibration_algorithms_sce_ua" class="nav-link" data-scroll-target="#sec-tech_calibration_algorithms_sce_ua"> <span class="header-section-number">10.3</span> Shuffled Complex Evoluation – University of Arizona</a>
  <ul class="collapse">
  <li><a href="#model-architecture" id="toc-model-architecture" class="nav-link" data-scroll-target="#model-architecture">Model architecture</a></li>
  <li><a href="#algorithm-parameters" id="toc-algorithm-parameters" class="nav-link" data-scroll-target="#algorithm-parameters">Algorithm parameters</a></li>
  </ul></li>
  <li><a href="#sec-tech_calibration_algorithms_uamc" id="toc-sec-tech_calibration_algorithms_uamc" class="nav-link" data-scroll-target="#sec-tech_calibration_algorithms_uamc"> <span class="header-section-number">10.4</span> Uniform Adaptive Monte Carlo</a>
  <ul class="collapse">
  <li><a href="#model-architecture-1" id="toc-model-architecture-1" class="nav-link" data-scroll-target="#model-architecture-1">Model architecture</a></li>
  <li><a href="#algorithm-parameters-1" id="toc-algorithm-parameters-1" class="nav-link" data-scroll-target="#algorithm-parameters-1">Algorithm parameters</a></li>
  </ul></li>
  <li><a href="#sec-tech_calibration_algorithms_rosenb" id="toc-sec-tech_calibration_algorithms_rosenb" class="nav-link" data-scroll-target="#sec-tech_calibration_algorithms_rosenb"> <span class="header-section-number">10.5</span> Coupled Latin Hypercube and Rosenbrock</a>
  <ul class="collapse">
  <li><a href="#model-architecture-2" id="toc-model-architecture-2" class="nav-link" data-scroll-target="#model-architecture-2">Model architecture</a></li>
  <li><a href="#algorithm-parameters-2" id="toc-algorithm-parameters-2" class="nav-link" data-scroll-target="#algorithm-parameters-2">Algorithm parameters</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="sec-tech_calibration_algorithms_intro" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="sec-tech_calibration_algorithms_intro"><span class="header-section-number">10.1</span> Introduction to the calibration module</h2>
<p>The module <em>Calibrator</em> of the <strong>RS Expert</strong> frame has been implemented for calibrating the parameters of the hydrological model. This module uses an objective function defined by the user and different algorithms to solve it.</p>
<p>The first algorithm, the Shuffled Complex Evolution – University of Arizona (SCE-UA), is a global optimization method <span class="citation" data-cites="duan_effective_1992 duan_shuffled_1993">(<a href="#ref-duan_effective_1992" role="doc-biblioref">Q. Duan, Sorooshian, and Gupta 1992</a>; <a href="#ref-duan_shuffled_1993" role="doc-biblioref">Q. Y. Duan, Gupta, and Sorooshian 1993</a>)</span> based on a synthesis of the best features from several existing algorithms, including the genetic algorithm, and introduces the concept of complex information exchange, so-called complex shuffling. The SCE-UA method was designed for solving problems encountered in conceptual watershed model calibration <span class="citation" data-cites="hapuarachchi_application_2001 ajami_calibration_2004 muttil_superior_2004 blasone_parameter_2007">(<a href="#ref-hapuarachchi_application_2001" role="doc-biblioref">Hapuarachchi, Li, and Wang 2001</a>; <a href="#ref-ajami_calibration_2004" role="doc-biblioref">Ajami et al. 2004</a>; <a href="#ref-muttil_superior_2004" role="doc-biblioref">Muttil and Liong 2004</a>; <a href="#ref-blasone_parameter_2007" role="doc-biblioref">Blasone, Madsen, and Rosbjerg 2007</a>)</span>, but has also been satisfyingly used in water resources management <span class="citation" data-cites="zhu_application_2006 lin_pareto_2008 wang_development_2010">(<a href="#ref-zhu_application_2006" role="doc-biblioref">Zhu, Wu, and Wu 2006</a>; <a href="#ref-lin_pareto_2008" role="doc-biblioref">Lin, Cheng, and Lin 2008</a>; <a href="#ref-wang_development_2010" role="doc-biblioref">Wang et al. 2010</a>)</span>.</p>
<p>The second algorithm is a variation of the Adaptive Markov Chain Monte Carlo, used since it can be interesting for solving complex problems in high dimensional spaces <span class="citation" data-cites="gilks_markov_1995 liu_monte_2004">(<a href="#ref-gilks_markov_1995" role="doc-biblioref">Gilks, Richardson, and Spiegelhalter 1995</a>; <a href="#ref-liu_monte_2004" role="doc-biblioref">Liu 2004</a>)</span>. It has been modified to an Uniform Adaptative Monte Carlo (UAMC) in this program to adjust the solution space after a defined group of simulations up to the convergence of the optimization. Variations of the Monte Carlo method are usually used in hydrological problem for parameterization optimization <span class="citation" data-cites="vrugt_effective_2003 jeremiah_efficient_2012">(<a href="#ref-vrugt_effective_2003" role="doc-biblioref">Vrugt et al. 2003</a>; <a href="#ref-jeremiah_efficient_2012" role="doc-biblioref">Jeremiah et al. 2012</a>)</span>.</p>
<p>The third and last algorithm used in RS&nbsp;MINERVE is the Coupled Latin Hypercube and Rosenbrock (CLHR) It couples the Latin Hypercube algorithm <span class="citation" data-cites="mckay_comparison_1979">(<a href="#ref-mckay_comparison_1979" role="doc-biblioref">McKay, Beckman, and Conover 1979</a>)</span> with the Rosenbrock algorithm <span class="citation" data-cites="rosenbrock_automatic_1960">(<a href="#ref-rosenbrock_automatic_1960" role="doc-biblioref">Rosenbrock 1960</a>)</span>, generating a powerful tool for optimization of complex problems. The latin hypercube algorithm has been usually used in hydrology for sampling the initial parameter space, combined the with other methods <span class="citation" data-cites="van_griensven_global_2006 kamali_comparison_2013">(<a href="#ref-van_griensven_global_2006" role="doc-biblioref">Griensven et al. 2006</a>; <a href="#ref-kamali_comparison_2013" role="doc-biblioref">Kamali, Ponnambalam, and Soulis 2013</a>)</span>. Rosenbrock algorithm has been also used for hydrological parameters optimisation <span class="citation" data-cites="abbott_distributed_1996">(<a href="#ref-abbott_distributed_1996" role="doc-biblioref">Abbott and Refsgaard 1996</a>)</span> or optimization of numerical functions <span class="citation" data-cites="kang_rosenbrock_2011">(<a href="#ref-kang_rosenbrock_2011" role="doc-biblioref">Kang, Li, and Ma 2011</a>)</span>.</p>
</section>
<section id="sec-tech_calibration_algorithms_of" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="sec-tech_calibration_algorithms_of"><span class="header-section-number">10.2</span> Objective function</h2>
<p>A flexible objective function (<span class="math inline">\(OF\)</span>) has been developed for the module of calibration aiming to be adapted to the user’s requirements. The indicators presented in <a href="tech_performance_indicators.html">Section&nbsp;<span>9</span></a> are used in this OF, each one weighted with a value defined by the user (<a href="#tbl-weights_indicators_of">Table&nbsp;<span>10.1</span></a>).</p>
<div id="tbl-weights_indicators_of" class="anchored">
<table class="table">
<caption>Table 10.1: Weights of the indicators for the objective function</caption>
<colgroup>
<col style="width: 47%">
<col style="width: 10%">
<col style="width: 22%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Indicator</th>
<th>Weight</th>
<th>Range of Values</th>
<th>Ideal value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nash</td>
<td>w<sub>1</sub></td>
<td>-∞ to 1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Nash-ln</td>
<td>w<sub>2</sub></td>
<td>-∞ to 1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Pearson Correlation Coefficient</td>
<td>w<sub>3</sub></td>
<td>-1 to 1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Kling-Gupta Efficiency (KGE)</td>
<td>w<sub>4</sub></td>
<td>-∞ to 1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Bias Score (BS)</td>
<td>w<sub>5</sub></td>
<td>-∞ to 1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Relative Root Mean Square Error (RRMSE)</td>
<td>w<sub>6</sub></td>
<td>0 to +∞</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Relative Volume Bias (RVB)</td>
<td>w<sub>7</sub></td>
<td>-∞ to +∞</td>
<td>0</td>
</tr>
<tr class="even">
<td>Normalized Peak Error (NPE)</td>
<td>w<sub>8</sub></td>
<td>-∞ to +∞</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Peirce Skill Score (PSS)</td>
<td>w<sub>9</sub></td>
<td>-1 to 1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Overall Accuracy (OA)</td>
<td>w<sub>10</sub></td>
<td>0 to 1</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
<p>The <span class="math inline">\(OF\)</span> is presented in <a href="#eq-CAL1">Equation&nbsp;<span>10.1</span></a> and takes into account the ideal values of each indicator. Thus, the <span class="math inline">\(OF\)</span> searches to maximize the first five and last two indicators (<span class="math inline">\(Nash\)</span>, <span class="math inline">\(Nash-ln\)</span>, <span class="math inline">\(Pearson\)</span>, <span class="math inline">\(Kling-Gupta\)</span>, <span class="math inline">\(BS\)</span>, <span class="math inline">\(PSS\)</span> and <span class="math inline">\(OA\)</span>) since their ideal value is equal to the maximum possible value and, at the same time, to minimize the value or the absolute value for the three other indicators (<span class="math inline">\(RRMSE\)</span>, <span class="math inline">\(RVB\)</span>, <span class="math inline">\(NPE\)</span>) since their ideal value corresponds to zero.</p>
<p><span id="eq-CAL1"><span class="math display">\[
OF = max(Nash \cdot w_{1} + Nashln \cdot w_{2} + Pearson \cdot w_{3} + KGE \cdot w_{4} + BS \cdot w_{5} - RRMSE \cdot w_{6} - \left| RVB \cdot w_{7} \right| - \left| NPE \cdot w_{8} \right| + PSS \cdot w_{9} + OA \cdot w_{10})
\qquad(10.1)\]</span></span></p>
</section>
<section id="sec-tech_calibration_algorithms_sce_ua" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-tech_calibration_algorithms_sce_ua"><span class="header-section-number">10.3</span> Shuffled Complex Evoluation – University of Arizona</h2>
<section id="model-architecture" class="level3">
<h3 class="anchored" data-anchor-id="model-architecture">Model architecture</h3>
<p>The Shuffled Complex Evolution – University of Arizona (SCE-UA) method was developed to obtain the traditional best parameter set and its underlying posterior distribution within a single optimization run. The goal is to find a single best parameter set in the feasible space. It starts with a random sample of points distributed throughout the feasible parameter space, and uses an adaptation of the Simplex Downhill search scheme <span class="citation" data-cites="nelder_simplex_1965">(<a href="#ref-nelder_simplex_1965" role="doc-biblioref">Nelder and Mead 1965</a>)</span> to continuously evolve the population toward better solutions in the search space, progressively relinquishing occupation of regions with lower posterior probability <span class="citation" data-cites="mariani_hybrid_2011">(<a href="#ref-mariani_hybrid_2011" role="doc-biblioref">Mariani et al. 2011</a>)</span>.</p>
<p>A general description of the steps of the SCE-UA method is given below <span class="citation" data-cites="duan_optimal_1994">(<a href="#ref-duan_optimal_1994" role="doc-biblioref">Q. Duan, Sorooshian, and Gupta 1994</a>)</span> and illustrated in <a href="#fig-flowchart_sce">Figure&nbsp;<span>10.1</span></a>.</p>
<p><em>Step 1</em></p>
<p>Generate sample: Sample <span class="math inline">\(NPT\)</span> points in the feasible parameter space and compute the criterion value at each point. In the absence of prior information on the location of the global optimum, use a uniform probability distribution to generate a sample.</p>
<p><em>Step 2</em></p>
<p>Rank points: Sort the <span class="math inline">\(NPT\)</span> points to increase criterion value so that the first point represents the point with the lowest criterion value and the last the one with the highest criterion value (assuming that the goal is to minimize the criterion value).</p>
<p><em>Step 3</em></p>
<p>Partition into complexes: Partition the <span class="math inline">\(NPT\)</span> points into <span class="math inline">\(NGS\)</span> complexes, each containing <span class="math inline">\(NPG\)</span> points. The complexes are partitioned in such a way that the first complex contains every <span class="math inline">\(NGS \cdot (k-1)+1\)</span> ranked point, the second complex contains every <span class="math inline">\(NGS \cdot (k-1)+2\)</span> ranked point, and so on, where <span class="math inline">\(k = 1,2,...,NPG\)</span>.</p>
<p><em>Step 4</em></p>
<p>Evolve each complex: Evolve each complex independently by taking <span class="math inline">\(NSPL\)</span> evolution steps, according to the Competitive Complex Evolution (CCE) algorithm. <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> illustrates how each evolution step is taken.</p>
<p><em>Step 5</em></p>
<p>Shuffle complexes: Combine the points in the evolved complexes into a single sample population; sort the sample population in order of increasing criterion value; re-partition or shuffle the sample population into <span class="math inline">\(NGS\)</span> complexes according to the procedure specified in the third step.</p>
<p><em>Step 6</em></p>
<p>Check convergence: If any of the pre-specified convergence criteria are satisfied, stop; otherwise, continue.</p>
<p><em>Step 7</em></p>
<p>Check complex number reduction: If <span class="math inline">\(MINGS\)</span> (the minimum number of complexes)&nbsp;<span class="math inline">\(&lt;&nbsp;NGS\)</span>, remove the complex with the lowest ranked points; set <span class="math inline">\(NGS=NGS-1\)</span> and <span class="math inline">\(NPT=NGS \cdot NPG\)</span>; and return to Step 4. If <span class="math inline">\(MINGS=NGS\)</span>, return to Step 4.</p>
<div id="fig-flowchart_sce" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fig-flowchart_sce.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.1: Flow chart of the shuffled complex evolution method (from <span class="citation" data-cites="duan_shuffled_1993">Q. Y. Duan, Gupta, and Sorooshian (<a href="#ref-duan_shuffled_1993" role="doc-biblioref">1993</a>)</span>), with <span class="math inline">\(V=n\)</span>, <span class="math inline">\(NGS=p\)</span>, <span class="math inline">\(NPG=m\)</span> and <span class="math inline">\(NPT=s\)</span></figcaption><p></p>
</figure>
</div>
<p>The SCE-UA method is explained in <a href="#fig-sce_ua_method">Figure&nbsp;<span>10.2</span></a> and <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> for a two dimensional case <span class="citation" data-cites="duan_optimal_1994">(<a href="#ref-duan_optimal_1994" role="doc-biblioref">Q. Duan, Sorooshian, and Gupta 1994</a>)</span>. The contour lines in <a href="#fig-sce_ua_method">Figure&nbsp;<span>10.2</span></a> and <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> represent a function surface having a global optimum located at (4,2) and a local optimum located at (1,2). <a href="#fig-sce_ua_method">Figure&nbsp;<span>10.2</span></a> (a) shows that a sample population containing <span class="math inline">\(NPT\)</span> (=10) points is divided into <span class="math inline">\(NGS\)</span> (=2) complexes. Each complex contains <span class="math inline">\(NPG\)</span> (=5) points which are marked by <strong>•</strong> and * respectively. <a href="#fig-sce_ua_method">Figure&nbsp;<span>10.2</span></a> (b) shows the locations of the points in the two independently evolved complexes at the end of the first cycle of evolution. It can be seen that one complex (marked by *) is converging towards the local optimum, while the other (marked by <strong>•</strong>) is converging toward the global optimum. The two evolved complexes are shuffled according to <em>Step 5</em>. <a href="#fig-sce_ua_method">Figure&nbsp;<span>10.2</span></a> (c) displays the new membership of the two evolved complexes after shuffling.</p>
<p><a href="#fig-sce_ua_method">Figure&nbsp;<span>10.2</span></a> (d) illustrates the two complexes at the end of the second cycle of evolution. It is clear that both complexes are now converging to the global optimum at the end of second cycle.</p>
<div id="fig-sce_ua_method" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fig-sce_ua_method.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.2: Illustration of the shuffled complex evolution (SCE-UA) method (from <span class="citation" data-cites="duan_optimal_1994">Q. Duan, Sorooshian, and Gupta (<a href="#ref-duan_optimal_1994" role="doc-biblioref">1994</a>)</span>)</figcaption><p></p>
</figure>
</div>
<p>The CCE algorithm is graphically illustrated in <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a>. The black dots (<strong>•</strong>) indicate the locations of the points in a complex before the evolution step is taken. A sub-complex containing <span class="math inline">\(NPS\)</span> (=3, i.e.&nbsp;forms a triangle in this case) points is selected according to a pre-specified probability distribution to initiate an evolution step.</p>
<p>The probability distribution is specified such that the better points have a higher chance of being chosen to form the sub-complex than the worse points. The symbol (*) represents the new points generated by the evolution steps. There are three types of evolution steps: reflection, contraction and mutation.</p>
<p><a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> (a), <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> (b) and <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> (d) illustrate the “reflection” step, which is implemented by reflecting the worst point in a sub-complex through the centroid of the other points. Since the reflected point has a lower criterion value than the worst point, the worst point is discarded and replaced by the new point. Thus an evolution step is completed.</p>
<p>In <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> (c), the new point is generated by a “contraction” step (the new point lies half-way between the worst point and the centroid of the other points), after rejecting a reflection step for not improving the criterion value.</p>
<p>In <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> (e), a “mutation” step is taken by random selection of a point in the feasible parameter space to replace the wrong point of the sub-complex. This is realized after a reflection step is attempted, but results in a wrong point, i.e.&nbsp;outside of the feasible parameter space. Another scenario in which a mutation step is taken is when both the reflection step and the contraction step do not improve the criterion value.</p>
<p>Finally, the <a href="#fig-sce_ua_steps">Figure&nbsp;<span>10.3</span></a> (f) shows the final complex after <span class="math inline">\(NSPL\)</span> (=5) evolution steps.</p>
<div id="fig-sce_ua_steps" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fig-sce_ua_steps.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.3: Illustration of the evolution steps taken by each complex (from <span class="citation" data-cites="duan_optimal_1994">Q. Duan, Sorooshian, and Gupta (<a href="#ref-duan_optimal_1994" role="doc-biblioref">1994</a>)</span>).</figcaption><p></p>
</figure>
</div>
</section>
<section id="algorithm-parameters" class="level3">
<h3 class="anchored" data-anchor-id="algorithm-parameters">Algorithm parameters</h3>
<p>Different parameters of the SCE-UA have to be defined by the user (<a href="#tbl-param_sce_ua_algorithm">Table&nbsp;<span>10.2</span></a>), as presented hereafter, and other parameters are directly calculated by the process.</p>
<p>An initial set of <span class="math inline">\(Nopt\)</span> parameters is given by the user or is assumed as random depending on the user’s needs and the used hydrological models. The other <span class="math inline">\(NPT-1\)</span> points (or parameters sets) are randomly created by the algorithm, depending on a <span class="math inline">\(SEED\)</span> value. The number of points <span class="math inline">\(NPG\)</span> in each complex corresponds to <span class="math inline">\(2 \cdot Nopt+1\)</span> and the number of points NPS in each sub-complex to <span class="math inline">\(Nopt+1\)</span> (It has to be noted that each point corresponds to a set of parameters). The number of evolution steps allowed for each complex before complex shuffling, <span class="math inline">\(NSPL\)</span>, is equal to <span class="math inline">\(NPG\)</span>. The number of complexes is defined as <span class="math inline">\(NGS\)</span>, which is assumed equal to MINGS according to the Duan investigation. Then, the total number of points <span class="math inline">\(NPT\)</span> in the entire sample population is <span class="math inline">\(NGS \cdot NPG\)</span>.</p>
<p>Three different convergence criteria are defined by the user:</p>
<ul>
<li><p>The maximum number of function evaluations (or iterations) <span class="math inline">\(MAXN\)</span>.</p></li>
<li><p>The number of shuffling loops (<span class="math inline">\(KSTOP\)</span>) in which the criterion value must change by a fixed percentage (<span class="math inline">\(PCENTO\)</span>) before optimization is finished.</p></li>
<li><p>The <span class="math inline">\(PEPS\)</span> parameter which provides a flag indicating whether parameter convergence is reached (it compares the value of <span class="math inline">\(PEPS\)</span> with the normalized geometric mean of parameter ranges).</p></li>
</ul>
<div id="tbl-param_sce_ua_algorithm" class="anchored">
<table class="table">
<caption>Table 10.2: Parameters of the SCE-UA algorithm</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 45%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Units</th>
<th>Description</th>
<th>Default Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MAXM</td>
<td>-</td>
<td>Maximum number of iterations</td>
<td>10000</td>
</tr>
<tr class="even">
<td>NGS</td>
<td>-</td>
<td>Number of complexes</td>
<td>3</td>
</tr>
<tr class="odd">
<td>KSTOP</td>
<td>-</td>
<td>Number of shuffling loops</td>
<td>10</td>
</tr>
<tr class="even">
<td>PCENTO</td>
<td>-</td>
<td>Criterion value on shuffling loops</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>PEPS</td>
<td>-</td>
<td>Convergence parameter</td>
<td>0.001</td>
</tr>
<tr class="even">
<td>SEED</td>
<td>-</td>
<td>Seed value</td>
<td>Random</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="sec-tech_calibration_algorithms_uamc" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="sec-tech_calibration_algorithms_uamc"><span class="header-section-number">10.4</span> Uniform Adaptive Monte Carlo</h2>
<section id="model-architecture-1" class="level3">
<h3 class="anchored" data-anchor-id="model-architecture-1">Model architecture</h3>
<p>The Uniform Adaptive Monte Carlo (UAMC) algorithm is based on the Monte Carlo experiments that rely on repeated random sampling to obtain simulation results <span class="citation" data-cites="gilks_markov_1995 liu_monte_2004">(<a href="#ref-gilks_markov_1995" role="doc-biblioref">Gilks, Richardson, and Spiegelhalter 1995</a>; <a href="#ref-liu_monte_2004" role="doc-biblioref">Liu 2004</a>)</span>; but has been modified in order to iteratively adjust the solution space.</p>
<p>The algorithm randomly launches a collection of simulations (block) and finds the better results in the solution space. Afterwards, the solution space is adjusted and a new group of simulations starts. The process is repeated until the optimization converges to the best set of parameters (<a href="#fig-flowchart_uamc">Figure&nbsp;<span>10.4</span></a>).</p>
</section>
<section id="algorithm-parameters-1" class="level3">
<h3 class="anchored" data-anchor-id="algorithm-parameters-1">Algorithm parameters</h3>
<p>Different parameters of the UAMC algorithm have to be defined by the user (<a href="#tbl-param_sce_uamc_algorithm">Table&nbsp;<span>10.3</span></a>), as presented hereafter.</p>
<p>A number of iterations <span class="math inline">\(ITGR\)</span> per group is defined for the optimization. Random values of parameters are used for each iteration of the group based on a <span class="math inline">\(SEED\)</span> value. Once the first group of iterations is finished, a number <span class="math inline">\(NUMBEST\)</span> of best values is applied for calculating the solutions space range for the next group of iterations. This solution space takes into account the minimum and the maximum values of each parameter providing the best values and adds an additional range <span class="math inline">\(COEFRANG\)</span>.</p>
<p>Finally, the optimization finishes when the convergence criterion (defined as <span class="math inline">\(ERR\)</span>) is achieved, or when the maximum number of iterations <span class="math inline">\(MAXN\)</span> is attained.</p>
<div id="tbl-param_sce_uamc_algorithm" class="anchored">
<table class="table">
<caption>Table 10.3: Parameters of the UAMC algorithm</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 63%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Units</th>
<th>Description</th>
<th>Default Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MAXN</td>
<td>-</td>
<td>Maximum number of iterations</td>
<td>2000</td>
</tr>
<tr class="even">
<td>ITGR</td>
<td>-</td>
<td>Number of iterations per group</td>
<td>100</td>
</tr>
<tr class="odd">
<td>NUMBEST</td>
<td>-</td>
<td>Number of best values taken into account for the next group calculation</td>
<td>5</td>
</tr>
<tr class="even">
<td>COEFRANG</td>
<td>-</td>
<td>Additional range coefficient</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>ERR</td>
<td>-</td>
<td>Error difference until convergence</td>
<td>0.001</td>
</tr>
<tr class="even">
<td>SEED</td>
<td>-</td>
<td>Seed value</td>
<td>Random</td>
</tr>
</tbody>
</table>
</div>
<div id="fig-flowchart_uamc" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fig-flowchart_uamc.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.4: Flow chart of the UAMC algorithm</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="sec-tech_calibration_algorithms_rosenb" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="sec-tech_calibration_algorithms_rosenb"><span class="header-section-number">10.5</span> Coupled Latin Hypercube and Rosenbrock</h2>
<section id="model-architecture-2" class="level3">
<h3 class="anchored" data-anchor-id="model-architecture-2">Model architecture</h3>
<p>The Coupled Latin Hypercube <span class="citation" data-cites="mckay_comparison_1979">(<a href="#ref-mckay_comparison_1979" role="doc-biblioref">McKay, Beckman, and Conover 1979</a>)</span> and the Rosenbrock algorithm <span class="citation" data-cites="rosenbrock_automatic_1960">(<a href="#ref-rosenbrock_automatic_1960" role="doc-biblioref">Rosenbrock 1960</a>)</span>, called hereafter CLHR, generates a powerful tool for optimization of complex problems. This combined algorithm can discretize a wide domain and then narrow your search to smaller sectors (<a href="#fig-operation_clhr">Figure&nbsp;<span>10.5</span></a>). Scanning of the space of possible solutions is performed by the Latin Hypercube. This algorithm allows pseudo-statistical sampling conditioned by the previous calculated solutions. The Latin hypercube is an evolution of Monte Carlo method, with more homogeneous samples achieved with fewer samples. An important advantage of this method is that the dimension of the problem is defined by the division of the latin hypercube and not by the number of parameters.</p>
<p>The best results from samples become the starting points required for Rosenbrock algorithm. The advantage of this subroutine calculation lies in the speed to obtain near optimal values. This algorithm is based on a gradient search, adjusting axis changes based on the direction of maximum enhancement, thus reducing the number of evaluations of the objective function.</p>
<div id="fig-operation_clhr" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fig-operation_clhr.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.5: Illustration of the operation of the CLHR algorithm</figcaption><p></p>
</figure>
</div>
<p>A general description of the steps of the CLHR method is given below:</p>
<p><em>Step 1</em></p>
<p>Generate sample: Generation and evaluation of a pseudorandom sample by a Latin hypercube within the feasible parameter space. If the size of the hypercube is greater, uncertainty is reduced within the domain of search.</p>
<p><em>Step 2</em></p>
<p>Rank points: The results obtained in the first step are ordered (<a href="#fig-operation_hypercube">Figure&nbsp;<span>10.6</span></a>). The best results from the Latin hypercube algorithm will serve as starting points to launch the Rosenbrock algorithm.</p>
<div id="fig-operation_hypercube" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fig-operation_hypercube.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.6: Illustration of the operation of the Latin Hypercube algorithm</figcaption><p></p>
</figure>
</div>
<p><em>Step 3</em></p>
<p>Launch of Rosenbrock: Rosenbrock algorithm starts at least once. This subroutine searches around the starting point the values that improve the objective function. Depending on whether the objective function improves or worsens, the parameters values are changed to advance or backward.</p>
<p><em>Step 4</em></p>
<p>Axes change: Axes are changed to orient the Cartesian axes to the direction of maximum improvement. For applying this change of axes, it should have obtained worse results in all directions of search and at least an improvement in one of these directions (remember each direction has 2 ways).</p>
<p><em>Step 5</em></p>
<p>The best result of all Rosenbrock releases is stored.</p>
<div id="fig-operation_rosenbrock" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fig-operation_rosenbrock.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 10.7: Illustration of the operation of the Rosenbrock algorithm</figcaption><p></p>
</figure>
</div>
</section>
<section id="algorithm-parameters-2" class="level3">
<h3 class="anchored" data-anchor-id="algorithm-parameters-2">Algorithm parameters</h3>
<p>Number of tests with the latin hypercube algorithm is equal to the parameter <span class="math inline">\(DivLH\)</span> (<span class="math inline">\(\geq 2\)</span>).The <span class="math inline">\(SEED\)</span> is responsible for generating the randomness of the sample.</p>
<p>The <span class="math inline">\(RLAUNCHES\)</span> (<span class="math inline">\(1 \geq RLAUNCHES \leq DivLH\)</span>) best results from the Latin Hypercube algorithm are used as starting points for the Rosenbrock algorithm.</p>
<p>The <span class="math inline">\(ALPHA\)</span> coefficient represents the increment in the direction of search if the objective function improves. The <span class="math inline">\(BETA\)</span> coefficient represents the movement if a worse result is obtained.</p>
<p>The <span class="math inline">\(STEPROS\)</span> parameter indicates the subdivisions for each parameter’s range. It is used to calculate value variations in each of the parameters (<span class="math inline">\(∆_i\)</span>) to be studied, as presented in <a href="#eq-CAL2">Equation&nbsp;<span>10.2</span></a>.</p>
<p><span id="eq-CAL2"><span class="math display">\[
\frac{MaxP{arameterValue}_{i} - Min{ParameterValue}_{i}}{STEPROS} = Delta_i
\qquad(10.2)\]</span></span></p>
<p>The optimization finishes when the convergence criterion (defined as <span class="math inline">\(ERR\)</span>) is achieved, or when the maximum number of iterations <span class="math inline">\(MAXN\)</span> is attained.</p>
<div id="tbl-param_sce_clhr_algorithm" class="anchored">
<table class="table">
<caption>Table 10.4: Parameters of the CLHR algorithm</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 45%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Units</th>
<th>Description</th>
<th>Default Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MAXN</td>
<td>-</td>
<td>Maximum number of iterations</td>
<td>2000</td>
</tr>
<tr class="even">
<td>DivLH</td>
<td>-</td>
<td>Latin hypercube division</td>
<td>50</td>
</tr>
<tr class="odd">
<td>SEED</td>
<td>-</td>
<td>Seed value</td>
<td>Random</td>
</tr>
<tr class="even">
<td>RLAUNCHES</td>
<td>-</td>
<td>Rosenbrock algorithm launches</td>
<td>2</td>
</tr>
<tr class="odd">
<td>ALPHA</td>
<td>-</td>
<td>Advance coefficient</td>
<td>3</td>
</tr>
<tr class="even">
<td>BETA</td>
<td>-</td>
<td>Backward coefficient</td>
<td>-0.5</td>
</tr>
<tr class="odd">
<td>STEPROS</td>
<td>-</td>
<td>Parameter range subdivision</td>
<td>40</td>
</tr>
<tr class="even">
<td>ERR</td>
<td>-</td>
<td>Convergence parameter</td>
<td>0.001</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-abbott_distributed_1996" class="csl-entry" role="doc-biblioentry">
Abbott, Michael B., and Jens Christian Refsgaard, eds. 1996. <em>Distributed <span>Hydrological</span> <span>Modelling</span></em>. Vol. 22. Water <span>Science</span> and <span>Technology</span> <span>Library</span>. Dordrecht: Springer Netherlands. <a href="https://doi.org/10.1007/978-94-009-0257-2">https://doi.org/10.1007/978-94-009-0257-2</a>.
</div>
<div id="ref-ajami_calibration_2004" class="csl-entry" role="doc-biblioentry">
Ajami, Newsha K., Hoshin Gupta, Thorsten Wagener, and Soroosh Sorooshian. 2004. <span>“Calibration of a Semi-Distributed Hydrologic Model for Streamflow Estimation Along a River System.”</span> <em>Journal of Hydrology</em> 298 (1-4): 112–35. <a href="https://doi.org/10.1016/j.jhydrol.2004.03.033">https://doi.org/10.1016/j.jhydrol.2004.03.033</a>.
</div>
<div id="ref-blasone_parameter_2007" class="csl-entry" role="doc-biblioentry">
Blasone, R.-S., H. Madsen, and Dan Rosbjerg. 2007. <span>“Parameter Estimation in Distributed Hydrological Modelling: Comparison of Global and Local Optimisation Techniques.”</span> <em>Hydrology Research</em> 38 (4-5): 451–76. <a href="https://doi.org/10.2166/nh.2007.024">https://doi.org/10.2166/nh.2007.024</a>.
</div>
<div id="ref-duan_shuffled_1993" class="csl-entry" role="doc-biblioentry">
Duan, Q. Y., V. K. Gupta, and S. Sorooshian. 1993. <span>“Shuffled Complex Evolution Approach for Effective and Efficient Global Minimization.”</span> <em>Journal of Optimization Theory and Applications</em> 76 (3): 501–21. <a href="https://doi.org/10.1007/BF00939380">https://doi.org/10.1007/BF00939380</a>.
</div>
<div id="ref-duan_effective_1992" class="csl-entry" role="doc-biblioentry">
Duan, Qingyun, Soroosh Sorooshian, and Vijai Gupta. 1992. <span>“Effective and Efficient Global Optimization for Conceptual Rainfall-Runoff Models.”</span> <em>Water Resources Research</em> 28 (4): 1015–31. <a href="https://doi.org/10.1029/91WR02985">https://doi.org/10.1029/91WR02985</a>.
</div>
<div id="ref-duan_optimal_1994" class="csl-entry" role="doc-biblioentry">
Duan, Qingyun, Soroosh Sorooshian, and Vijai K. Gupta. 1994. <span>“Optimal Use of the <span>SCE</span>-<span>UA</span> Global Optimization Method for Calibrating Watershed Models.”</span> <em>Journal of Hydrology</em> 158 (3-4): 265–84. <a href="https://doi.org/10.1016/0022-1694(94)90057-4">https://doi.org/10.1016/0022-1694(94)90057-4</a>.
</div>
<div id="ref-gilks_markov_1995" class="csl-entry" role="doc-biblioentry">
Gilks, W. R., S. Richardson, and David Spiegelhalter, eds. 1995. <em>Markov <span>Chain</span> <span>Monte</span> <span>Carlo</span> in <span>Practice</span></em>. 0th ed. Chapman; Hall/CRC. <a href="https://doi.org/10.1201/b14835">https://doi.org/10.1201/b14835</a>.
</div>
<div id="ref-van_griensven_global_2006" class="csl-entry" role="doc-biblioentry">
Griensven, A. van, T. Meixner, S. Grunwald, T. Bishop, M. Diluzio, and R. Srinivasan. 2006. <span>“A Global Sensitivity Analysis Tool for the Parameters of Multi-Variable Catchment Models.”</span> <em>Journal of Hydrology</em> 324 (1-4): 10–23. <a href="https://doi.org/10.1016/j.jhydrol.2005.09.008">https://doi.org/10.1016/j.jhydrol.2005.09.008</a>.
</div>
<div id="ref-hapuarachchi_application_2001" class="csl-entry" role="doc-biblioentry">
Hapuarachchi, H. A. Prasantha, Zhijia Li, and Shouhui Wang. 2001. <span>“Application of <span>SCE</span>-<span>UA</span> <span>Method</span> for <span>Calibrating</span> the <span>Xinanjiang</span> <span>Watershed</span> <span>Model</span>.”</span> <em>Journal of Lake Sciences</em> 12 (4): 304–14.
</div>
<div id="ref-jeremiah_efficient_2012" class="csl-entry" role="doc-biblioentry">
Jeremiah, Erwin, Scott A. Sisson, Ashish Sharma, and Lucy Marshall. 2012. <span>“Efficient Hydrological Model Parameter Optimization with <span>Sequential</span> <span>Monte</span> <span>Carlo</span> Sampling.”</span> <em>Environmental Modelling &amp; Software</em> 38 (December): 283–95. <a href="https://doi.org/10.1016/j.envsoft.2012.07.001">https://doi.org/10.1016/j.envsoft.2012.07.001</a>.
</div>
<div id="ref-kamali_comparison_2013" class="csl-entry" role="doc-biblioentry">
Kamali, M., K. Ponnambalam, and E. D. Soulis. 2013. <span>“Comparison of Several Heuristic Approaches to Calibration of <span>WATCLASS</span> Hydrologic Model.”</span> <em>Canadian Water Resources Journal</em> 38 (1): 40–46. <a href="https://doi.org/10.1080/07011784.2013.774154">https://doi.org/10.1080/07011784.2013.774154</a>.
</div>
<div id="ref-kang_rosenbrock_2011" class="csl-entry" role="doc-biblioentry">
Kang, Fei, Junjie Li, and Zhenyue Ma. 2011. <span>“Rosenbrock Artificial Bee Colony Algorithm for Accurate Global Optimization of Numerical Functions.”</span> <em>Information Sciences</em> 181 (16): 3508–31. <a href="https://doi.org/10.1016/j.ins.2011.04.024">https://doi.org/10.1016/j.ins.2011.04.024</a>.
</div>
<div id="ref-lin_pareto_2008" class="csl-entry" role="doc-biblioentry">
Lin, Jian-Yi, Chun-Tian Cheng, and Tao Lin. 2008. <span>“A <span>Pareto</span> <span>Strength</span> <span>SCE</span>-<span>UA</span> <span>Algorithm</span> for <span>Reservoir</span> <span>Optimization</span> <span>Operation</span>.”</span> In <em>2008 <span>Fourth</span> <span>International</span> <span>Conference</span> on <span>Natural</span> <span>Computation</span></em>, 406–12. Jinan, Shandong, China: IEEE. <a href="https://doi.org/10.1109/ICNC.2008.84">https://doi.org/10.1109/ICNC.2008.84</a>.
</div>
<div id="ref-liu_monte_2004" class="csl-entry" role="doc-biblioentry">
Liu, Jun S. 2004. <em>Monte <span>Carlo</span> <span>Strategies</span> in <span>Scientific</span> <span>Computing</span></em>. Springer <span>Series</span> in <span>Statistics</span>. New York, NY: Springer New York. <a href="https://doi.org/10.1007/978-0-387-76371-2">https://doi.org/10.1007/978-0-387-76371-2</a>.
</div>
<div id="ref-mariani_hybrid_2011" class="csl-entry" role="doc-biblioentry">
Mariani, Viviana Cocco, Luiz Guilherme Justi Luvizotto, Fábio Alessandro Guerra, and Leandro dos Santos Coelho. 2011. <span>“A Hybrid Shuffled Complex Evolution Approach Based on Differential Evolution for Unconstrained Optimization.”</span> <em>Applied Mathematics and Computation</em> 217 (12): 5822–29. <a href="https://doi.org/10.1016/j.amc.2010.12.064">https://doi.org/10.1016/j.amc.2010.12.064</a>.
</div>
<div id="ref-mckay_comparison_1979" class="csl-entry" role="doc-biblioentry">
McKay, M. D., R. J. Beckman, and W. J. Conover. 1979. <span>“A <span>Comparison</span> of <span>Three</span> <span>Methods</span> for <span>Selecting</span> <span>Values</span> of <span>Input</span> <span>Variables</span> in the <span>Analysis</span> of <span>Output</span> from a <span>Computer</span> <span>Code</span>.”</span> <em>Technometrics</em> 21 (2): 239. <a href="https://doi.org/10.2307/1268522">https://doi.org/10.2307/1268522</a>.
</div>
<div id="ref-muttil_superior_2004" class="csl-entry" role="doc-biblioentry">
Muttil, Nitin, and Shie-Yui Liong. 2004. <span>“Superior <span>Exploration</span>–<span>Exploitation</span> <span>Balance</span> in <span>Shuffled</span> <span>Complex</span> <span>Evolution</span>.”</span> <em>Journal of Hydraulic Engineering</em> 130 (12): 1202–5. <a href="https://doi.org/10.1061/(ASCE)0733-9429(2004)130:12(1202)">https://doi.org/10.1061/(ASCE)0733-9429(2004)130:12(1202)</a>.
</div>
<div id="ref-nelder_simplex_1965" class="csl-entry" role="doc-biblioentry">
Nelder, J. A., and R. Mead. 1965. <span>“A <span>Simplex</span> <span>Method</span> for <span>Function</span> <span>Minimization</span>.”</span> <em>The Computer Journal</em> 7 (4): 308–13. <a href="https://doi.org/10.1093/comjnl/7.4.308">https://doi.org/10.1093/comjnl/7.4.308</a>.
</div>
<div id="ref-rosenbrock_automatic_1960" class="csl-entry" role="doc-biblioentry">
Rosenbrock, H. H. 1960. <span>“An <span>Automatic</span> <span>Method</span> for <span>Finding</span> the <span>Greatest</span> or <span>Least</span> <span>Value</span> of a <span>Function</span>.”</span> <em>The Computer Journal</em> 3 (3): 175–84. <a href="https://doi.org/10.1093/comjnl/3.3.175">https://doi.org/10.1093/comjnl/3.3.175</a>.
</div>
<div id="ref-vrugt_effective_2003" class="csl-entry" role="doc-biblioentry">
Vrugt, Jasper A., Hoshin V. Gupta, Luis A. Bastidas, Willem Bouten, and Soroosh Sorooshian. 2003. <span>“Effective and Efficient Algorithm for Multiobjective Optimization of Hydrologic Models.”</span> <em>Water Resources Research</em> 39 (8). <a href="https://doi.org/10.1029/2002WR001746">https://doi.org/10.1029/2002WR001746</a>.
</div>
<div id="ref-wang_development_2010" class="csl-entry" role="doc-biblioentry">
Wang, Lei, Cho Thanda Nyunt, Toshio Koike, Oliver Saavedra, Lan Chau Nguyen, and Tran van Sap. 2010. <span>“Development of an Integrated Modeling System for Improved Multi-Objective Reservoir Operation.”</span> <em>Frontiers of Architecture and Civil Engineering in China</em> 4 (1): 47–55. <a href="https://doi.org/10.1007/s11709-010-0001-x">https://doi.org/10.1007/s11709-010-0001-x</a>.
</div>
<div id="ref-zhu_application_2006" class="csl-entry" role="doc-biblioentry">
Zhu, Xiaobin, Jichun Wu, and Jianfeng Wu. 2006. <span>“Application of <span>SCE</span>-<span>UA</span> to <span>Optimize</span> the <span>Management</span> <span>Model</span> of <span>Groundwater</span> <span>Resources</span> in <span>Deep</span> <span>Aquifers</span> of the <span>Yangtze</span> <span>Delta</span>.”</span> In <em>First <span>International</span> <span>Multi</span>-<span>Symposiums</span> on <span>Computer</span> and <span>Computational</span> <span>Sciences</span> (<span>IMSCCS</span>’06)</em>, 2:303–8. <a href="https://doi.org/10.1109/IMSCCS.2006.192">https://doi.org/10.1109/IMSCCS.2006.192</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tech_performance_indicators.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Performance indicators</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./tech_stochastic_equations.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Stochastic equations</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>