# Plugins {#sec-user_plugins}

Needs and requests in terms of hydrological and hydraulic modelling
differ a lot among users. This is why sometimes, tools need to be
developped for specific applications. To answer these particular
requests, a plugin module has been developped to enable integration of
additional tools into RS MINERVE.  

## Options for the integration of plugins

Plugins are additional tools integrated in RS MINERVE. They are
developed by the RS MINERVE Group on request of users of the RS MINERVE
community that are willing to fund their developments. Depending on
their wish to share or not the developed plugin, three different
possibilities exist:

-   **Integration in RS MINERVE**: The plugin is directly integrated in RS MINERVE and therefore available to all users at installation.

-   **Plugin available for download on a website**: The founder can decide that the plugin should not be part of RS MINERVE but freely 
    available for download on a webpage (CREALP website or company website).

-   **Private plugin**: The funder can decide not to share the plugin.

## Plugin Manager (under development)

The Plugin manager will allow integration of plugins not yet available
in RS MINERVE (available for download on a webpage). This part is still
under development. However, plugins can already be used trough addition
of dll files. In case of questions, please contact the RS MINERVE Group
trough the email contact indicated on the Plugin Manager.

## Plugins documentation

The documentation of the plugin is specific to each plugin and not part
of the official User and Technical manuals of RS MINERVE.