on:
  push:
  pull_request:
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render and deploy Manual

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          # To install LaTeX to build PDF book 
          tinytex: false 
          # uncomment below and fill to pin a version
          # version: 0.9.105

      # Install any computing dependency you may need, usually either python and Jupyter or R
      # More specific examples will be shared on quarto-dev/quarto-actions project

      - name: Render book to html
        # Add any command line argument needed
        run: |
          quarto render --to html
      - name: Deploy 🚀
      #   # only deploy when push to main
      #   # if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: docs
          
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Pushes docs folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'docs'
        destination_repo: 'crealp/rsminerve'
        destination_folder: 'RSMinerve/bin/Release/Help'
        user_email: 'theo.baracchini@crealp.vs.ch'
        user_name: 'theoCREALP'
        commit_msg: '[GHA] Update of the manual files.'     
